/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as RestablecerRouteImport } from './routes/restablecer'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PreciosRouteImport } from './routes/precios'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as SuperadminTenantIdRouteImport } from './routes/superadmin.$tenantId'
import { Route as SucursalSucursalSlugRouteImport } from './routes/sucursal.$sucursalSlug'
import { Route as InvitacionTokenRouteImport } from './routes/invitacion.$token'
import { Route as AuthCompletarRouteImport } from './routes/auth.completar'
import { Route as AdminSuscripcionRouteImport } from './routes/admin.suscripcion'
import { Route as AdminSucursalesRouteImport } from './routes/admin.sucursales'
import { Route as AdminQrRouteImport } from './routes/admin.qr'
import { Route as AdminOpinionesRouteImport } from './routes/admin.opiniones'
import { Route as AdminModificadoresRouteImport } from './routes/admin.modificadores'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminEquipoRouteImport } from './routes/admin.equipo'
import { Route as AdminEmpresaRouteImport } from './routes/admin.empresa'
import { Route as AdminDisenoRouteImport } from './routes/admin.diseno'
import { Route as SlugSucursalSucursalSlugRouteImport } from './routes/$slug.sucursal.$sucursalSlug'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerRoute = RestablecerRouteImport.update({
  id: '/restablecer',
  path: '/restablecer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciosRoute = PreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminTenantIdRoute = SuperadminTenantIdRouteImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => SuperadminRoute,
} as any)
const SucursalSucursalSlugRoute = SucursalSucursalSlugRouteImport.update({
  id: '/sucursal/$sucursalSlug',
  path: '/sucursal/$sucursalSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionTokenRoute = InvitacionTokenRouteImport.update({
  id: '/invitacion/$token',
  path: '/invitacion/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompletarRoute = AuthCompletarRouteImport.update({
  id: '/auth/completar',
  path: '/auth/completar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuscripcionRoute = AdminSuscripcionRouteImport.update({
  id: '/admin/suscripcion',
  path: '/admin/suscripcion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSucursalesRoute = AdminSucursalesRouteImport.update({
  id: '/admin/sucursales',
  path: '/admin/sucursales',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQrRoute = AdminQrRouteImport.update({
  id: '/admin/qr',
  path: '/admin/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpinionesRoute = AdminOpinionesRouteImport.update({
  id: '/admin/opiniones',
  path: '/admin/opiniones',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModificadoresRoute = AdminModificadoresRouteImport.update({
  id: '/admin/modificadores',
  path: '/admin/modificadores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/admin/menu',
  path: '/admin/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEquipoRoute = AdminEquipoRouteImport.update({
  id: '/admin/equipo',
  path: '/admin/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmpresaRoute = AdminEmpresaRouteImport.update({
  id: '/admin/empresa',
  path: '/admin/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDisenoRoute = AdminDisenoRouteImport.update({
  id: '/admin/diseno',
  path: '/admin/diseno',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugSucursalSucursalSlugRoute =
  SlugSucursalSucursalSlugRouteImport.update({
    id: '/$slug/sucursal/$sucursalSlug',
    path: '/$slug/sucursal/$sucursalSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/precios': typeof PreciosRoute
  '/privacidad': typeof PrivacidadRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/diseno': typeof AdminDisenoRoute
  '/admin/empresa': typeof AdminEmpresaRoute
  '/admin/equipo': typeof AdminEquipoRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/modificadores': typeof AdminModificadoresRoute
  '/admin/opiniones': typeof AdminOpinionesRoute
  '/admin/qr': typeof AdminQrRoute
  '/admin/sucursales': typeof AdminSucursalesRoute
  '/admin/suscripcion': typeof AdminSuscripcionRoute
  '/auth/completar': typeof AuthCompletarRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/sucursal/$sucursalSlug': typeof SucursalSucursalSlugRoute
  '/superadmin/$tenantId': typeof SuperadminTenantIdRoute
  '/$slug/': typeof SlugIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$slug/sucursal/$sucursalSlug': typeof SlugSucursalSucursalSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/precios': typeof PreciosRoute
  '/privacidad': typeof PrivacidadRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/diseno': typeof AdminDisenoRoute
  '/admin/empresa': typeof AdminEmpresaRoute
  '/admin/equipo': typeof AdminEquipoRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/modificadores': typeof AdminModificadoresRoute
  '/admin/opiniones': typeof AdminOpinionesRoute
  '/admin/qr': typeof AdminQrRoute
  '/admin/sucursales': typeof AdminSucursalesRoute
  '/admin/suscripcion': typeof AdminSuscripcionRoute
  '/auth/completar': typeof AuthCompletarRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/sucursal/$sucursalSlug': typeof SucursalSucursalSlugRoute
  '/superadmin/$tenantId': typeof SuperadminTenantIdRoute
  '/$slug': typeof SlugIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$slug/sucursal/$sucursalSlug': typeof SlugSucursalSucursalSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/precios': typeof PreciosRoute
  '/privacidad': typeof PrivacidadRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/diseno': typeof AdminDisenoRoute
  '/admin/empresa': typeof AdminEmpresaRoute
  '/admin/equipo': typeof AdminEquipoRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/modificadores': typeof AdminModificadoresRoute
  '/admin/opiniones': typeof AdminOpinionesRoute
  '/admin/qr': typeof AdminQrRoute
  '/admin/sucursales': typeof AdminSucursalesRoute
  '/admin/suscripcion': typeof AdminSuscripcionRoute
  '/auth/completar': typeof AuthCompletarRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/sucursal/$sucursalSlug': typeof SucursalSucursalSlugRoute
  '/superadmin/$tenantId': typeof SuperadminTenantIdRoute
  '/$slug/': typeof SlugIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$slug/sucursal/$sucursalSlug': typeof SlugSucursalSucursalSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/demo'
    | '/login'
    | '/onboarding'
    | '/precios'
    | '/privacidad'
    | '/recuperar'
    | '/registro'
    | '/restablecer'
    | '/superadmin'
    | '/admin/diseno'
    | '/admin/empresa'
    | '/admin/equipo'
    | '/admin/menu'
    | '/admin/modificadores'
    | '/admin/opiniones'
    | '/admin/qr'
    | '/admin/sucursales'
    | '/admin/suscripcion'
    | '/auth/completar'
    | '/invitacion/$token'
    | '/sucursal/$sucursalSlug'
    | '/superadmin/$tenantId'
    | '/$slug/'
    | '/admin/'
    | '/$slug/sucursal/$sucursalSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/demo'
    | '/login'
    | '/onboarding'
    | '/precios'
    | '/privacidad'
    | '/recuperar'
    | '/registro'
    | '/restablecer'
    | '/superadmin'
    | '/admin/diseno'
    | '/admin/empresa'
    | '/admin/equipo'
    | '/admin/menu'
    | '/admin/modificadores'
    | '/admin/opiniones'
    | '/admin/qr'
    | '/admin/sucursales'
    | '/admin/suscripcion'
    | '/auth/completar'
    | '/invitacion/$token'
    | '/sucursal/$sucursalSlug'
    | '/superadmin/$tenantId'
    | '/$slug'
    | '/admin'
    | '/$slug/sucursal/$sucursalSlug'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/demo'
    | '/login'
    | '/onboarding'
    | '/precios'
    | '/privacidad'
    | '/recuperar'
    | '/registro'
    | '/restablecer'
    | '/superadmin'
    | '/admin/diseno'
    | '/admin/empresa'
    | '/admin/equipo'
    | '/admin/menu'
    | '/admin/modificadores'
    | '/admin/opiniones'
    | '/admin/qr'
    | '/admin/sucursales'
    | '/admin/suscripcion'
    | '/auth/completar'
    | '/invitacion/$token'
    | '/sucursal/$sucursalSlug'
    | '/superadmin/$tenantId'
    | '/$slug/'
    | '/admin/'
    | '/$slug/sucursal/$sucursalSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PreciosRoute: typeof PreciosRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RecuperarRoute: typeof RecuperarRoute
  RegistroRoute: typeof RegistroRoute
  RestablecerRoute: typeof RestablecerRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  AdminDisenoRoute: typeof AdminDisenoRoute
  AdminEmpresaRoute: typeof AdminEmpresaRoute
  AdminEquipoRoute: typeof AdminEquipoRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminModificadoresRoute: typeof AdminModificadoresRoute
  AdminOpinionesRoute: typeof AdminOpinionesRoute
  AdminQrRoute: typeof AdminQrRoute
  AdminSucursalesRoute: typeof AdminSucursalesRoute
  AdminSuscripcionRoute: typeof AdminSuscripcionRoute
  AuthCompletarRoute: typeof AuthCompletarRoute
  InvitacionTokenRoute: typeof InvitacionTokenRoute
  SucursalSucursalSlugRoute: typeof SucursalSucursalSlugRoute
  SlugIndexRoute: typeof SlugIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SlugSucursalSucursalSlugRoute: typeof SlugSucursalSucursalSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer': {
      id: '/restablecer'
      path: '/restablecer'
      fullPath: '/restablecer'
      preLoaderRoute: typeof RestablecerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precios': {
      id: '/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof PreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/$tenantId': {
      id: '/superadmin/$tenantId'
      path: '/$tenantId'
      fullPath: '/superadmin/$tenantId'
      preLoaderRoute: typeof SuperadminTenantIdRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/sucursal/$sucursalSlug': {
      id: '/sucursal/$sucursalSlug'
      path: '/sucursal/$sucursalSlug'
      fullPath: '/sucursal/$sucursalSlug'
      preLoaderRoute: typeof SucursalSucursalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitacion/$token': {
      id: '/invitacion/$token'
      path: '/invitacion/$token'
      fullPath: '/invitacion/$token'
      preLoaderRoute: typeof InvitacionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/completar': {
      id: '/auth/completar'
      path: '/auth/completar'
      fullPath: '/auth/completar'
      preLoaderRoute: typeof AuthCompletarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suscripcion': {
      id: '/admin/suscripcion'
      path: '/admin/suscripcion'
      fullPath: '/admin/suscripcion'
      preLoaderRoute: typeof AdminSuscripcionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sucursales': {
      id: '/admin/sucursales'
      path: '/admin/sucursales'
      fullPath: '/admin/sucursales'
      preLoaderRoute: typeof AdminSucursalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/qr': {
      id: '/admin/qr'
      path: '/admin/qr'
      fullPath: '/admin/qr'
      preLoaderRoute: typeof AdminQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/opiniones': {
      id: '/admin/opiniones'
      path: '/admin/opiniones'
      fullPath: '/admin/opiniones'
      preLoaderRoute: typeof AdminOpinionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/modificadores': {
      id: '/admin/modificadores'
      path: '/admin/modificadores'
      fullPath: '/admin/modificadores'
      preLoaderRoute: typeof AdminModificadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/admin/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/equipo': {
      id: '/admin/equipo'
      path: '/admin/equipo'
      fullPath: '/admin/equipo'
      preLoaderRoute: typeof AdminEquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/empresa': {
      id: '/admin/empresa'
      path: '/admin/empresa'
      fullPath: '/admin/empresa'
      preLoaderRoute: typeof AdminEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diseno': {
      id: '/admin/diseno'
      path: '/admin/diseno'
      fullPath: '/admin/diseno'
      preLoaderRoute: typeof AdminDisenoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/sucursal/$sucursalSlug': {
      id: '/$slug/sucursal/$sucursalSlug'
      path: '/$slug/sucursal/$sucursalSlug'
      fullPath: '/$slug/sucursal/$sucursalSlug'
      preLoaderRoute: typeof SlugSucursalSucursalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SuperadminRouteChildren {
  SuperadminTenantIdRoute: typeof SuperadminTenantIdRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminTenantIdRoute: SuperadminTenantIdRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PreciosRoute: PreciosRoute,
  PrivacidadRoute: PrivacidadRoute,
  RecuperarRoute: RecuperarRoute,
  RegistroRoute: RegistroRoute,
  RestablecerRoute: RestablecerRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  AdminDisenoRoute: AdminDisenoRoute,
  AdminEmpresaRoute: AdminEmpresaRoute,
  AdminEquipoRoute: AdminEquipoRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminModificadoresRoute: AdminModificadoresRoute,
  AdminOpinionesRoute: AdminOpinionesRoute,
  AdminQrRoute: AdminQrRoute,
  AdminSucursalesRoute: AdminSucursalesRoute,
  AdminSuscripcionRoute: AdminSuscripcionRoute,
  AuthCompletarRoute: AuthCompletarRoute,
  InvitacionTokenRoute: InvitacionTokenRoute,
  SucursalSucursalSlugRoute: SucursalSucursalSlugRoute,
  SlugIndexRoute: SlugIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  SlugSucursalSucursalSlugRoute: SlugSucursalSucursalSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
